// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ronin.proto

package bp

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Buffer struct {
	Raw                  []byte   `protobuf:"bytes,1,opt,name=Raw,proto3" json:"Raw,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Buffer) Reset()         { *m = Buffer{} }
func (m *Buffer) String() string { return proto.CompactTextString(m) }
func (*Buffer) ProtoMessage()    {}
func (*Buffer) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6429a795f1f5a23, []int{0}
}

func (m *Buffer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Buffer.Unmarshal(m, b)
}
func (m *Buffer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Buffer.Marshal(b, m, deterministic)
}
func (m *Buffer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Buffer.Merge(m, src)
}
func (m *Buffer) XXX_Size() int {
	return xxx_messageInfo_Buffer.Size(m)
}
func (m *Buffer) XXX_DiscardUnknown() {
	xxx_messageInfo_Buffer.DiscardUnknown(m)
}

var xxx_messageInfo_Buffer proto.InternalMessageInfo

func (m *Buffer) GetRaw() []byte {
	if m != nil {
		return m.Raw
	}
	return nil
}

type TrafficFromClient struct {
	Buffer               *Buffer  `protobuf:"bytes,1,opt,name=Buffer,proto3" json:"Buffer,omitempty"`
	ToHost               string   `protobuf:"bytes,2,opt,name=ToHost,proto3" json:"ToHost,omitempty"`
	ToPort               uint32   `protobuf:"varint,3,opt,name=ToPort,proto3" json:"ToPort,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrafficFromClient) Reset()         { *m = TrafficFromClient{} }
func (m *TrafficFromClient) String() string { return proto.CompactTextString(m) }
func (*TrafficFromClient) ProtoMessage()    {}
func (*TrafficFromClient) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6429a795f1f5a23, []int{1}
}

func (m *TrafficFromClient) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrafficFromClient.Unmarshal(m, b)
}
func (m *TrafficFromClient) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrafficFromClient.Marshal(b, m, deterministic)
}
func (m *TrafficFromClient) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrafficFromClient.Merge(m, src)
}
func (m *TrafficFromClient) XXX_Size() int {
	return xxx_messageInfo_TrafficFromClient.Size(m)
}
func (m *TrafficFromClient) XXX_DiscardUnknown() {
	xxx_messageInfo_TrafficFromClient.DiscardUnknown(m)
}

var xxx_messageInfo_TrafficFromClient proto.InternalMessageInfo

func (m *TrafficFromClient) GetBuffer() *Buffer {
	if m != nil {
		return m.Buffer
	}
	return nil
}

func (m *TrafficFromClient) GetToHost() string {
	if m != nil {
		return m.ToHost
	}
	return ""
}

func (m *TrafficFromClient) GetToPort() uint32 {
	if m != nil {
		return m.ToPort
	}
	return 0
}

type TrafficFromServer struct {
	Buffer               *Buffer  `protobuf:"bytes,1,opt,name=Buffer,proto3" json:"Buffer,omitempty"`
	FromHost             string   `protobuf:"bytes,2,opt,name=FromHost,proto3" json:"FromHost,omitempty"`
	FromPort             uint32   `protobuf:"varint,3,opt,name=FromPort,proto3" json:"FromPort,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrafficFromServer) Reset()         { *m = TrafficFromServer{} }
func (m *TrafficFromServer) String() string { return proto.CompactTextString(m) }
func (*TrafficFromServer) ProtoMessage()    {}
func (*TrafficFromServer) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6429a795f1f5a23, []int{2}
}

func (m *TrafficFromServer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrafficFromServer.Unmarshal(m, b)
}
func (m *TrafficFromServer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrafficFromServer.Marshal(b, m, deterministic)
}
func (m *TrafficFromServer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrafficFromServer.Merge(m, src)
}
func (m *TrafficFromServer) XXX_Size() int {
	return xxx_messageInfo_TrafficFromServer.Size(m)
}
func (m *TrafficFromServer) XXX_DiscardUnknown() {
	xxx_messageInfo_TrafficFromServer.DiscardUnknown(m)
}

var xxx_messageInfo_TrafficFromServer proto.InternalMessageInfo

func (m *TrafficFromServer) GetBuffer() *Buffer {
	if m != nil {
		return m.Buffer
	}
	return nil
}

func (m *TrafficFromServer) GetFromHost() string {
	if m != nil {
		return m.FromHost
	}
	return ""
}

func (m *TrafficFromServer) GetFromPort() uint32 {
	if m != nil {
		return m.FromPort
	}
	return 0
}

type ForwardRequest struct {
	TargetHost           string   `protobuf:"bytes,1,opt,name=TargetHost,proto3" json:"TargetHost,omitempty"`
	TargetPort           uint32   `protobuf:"varint,2,opt,name=TargetPort,proto3" json:"TargetPort,omitempty"`
	RoninPort            uint32   `protobuf:"varint,3,opt,name=RoninPort,proto3" json:"RoninPort,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForwardRequest) Reset()         { *m = ForwardRequest{} }
func (m *ForwardRequest) String() string { return proto.CompactTextString(m) }
func (*ForwardRequest) ProtoMessage()    {}
func (*ForwardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6429a795f1f5a23, []int{3}
}

func (m *ForwardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForwardRequest.Unmarshal(m, b)
}
func (m *ForwardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForwardRequest.Marshal(b, m, deterministic)
}
func (m *ForwardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForwardRequest.Merge(m, src)
}
func (m *ForwardRequest) XXX_Size() int {
	return xxx_messageInfo_ForwardRequest.Size(m)
}
func (m *ForwardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ForwardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ForwardRequest proto.InternalMessageInfo

func (m *ForwardRequest) GetTargetHost() string {
	if m != nil {
		return m.TargetHost
	}
	return ""
}

func (m *ForwardRequest) GetTargetPort() uint32 {
	if m != nil {
		return m.TargetPort
	}
	return 0
}

func (m *ForwardRequest) GetRoninPort() uint32 {
	if m != nil {
		return m.RoninPort
	}
	return 0
}

type ForwardResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=Ok,proto3" json:"Ok,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=Reason,proto3" json:"Reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForwardResponse) Reset()         { *m = ForwardResponse{} }
func (m *ForwardResponse) String() string { return proto.CompactTextString(m) }
func (*ForwardResponse) ProtoMessage()    {}
func (*ForwardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6429a795f1f5a23, []int{4}
}

func (m *ForwardResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForwardResponse.Unmarshal(m, b)
}
func (m *ForwardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForwardResponse.Marshal(b, m, deterministic)
}
func (m *ForwardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForwardResponse.Merge(m, src)
}
func (m *ForwardResponse) XXX_Size() int {
	return xxx_messageInfo_ForwardResponse.Size(m)
}
func (m *ForwardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ForwardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ForwardResponse proto.InternalMessageInfo

func (m *ForwardResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *ForwardResponse) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func init() {
	proto.RegisterType((*Buffer)(nil), "bp.Buffer")
	proto.RegisterType((*TrafficFromClient)(nil), "bp.TrafficFromClient")
	proto.RegisterType((*TrafficFromServer)(nil), "bp.TrafficFromServer")
	proto.RegisterType((*ForwardRequest)(nil), "bp.ForwardRequest")
	proto.RegisterType((*ForwardResponse)(nil), "bp.ForwardResponse")
}

func init() { proto.RegisterFile("ronin.proto", fileDescriptor_f6429a795f1f5a23) }

var fileDescriptor_f6429a795f1f5a23 = []byte{
	// 320 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0x4e, 0xf2, 0x40,
	0x14, 0x85, 0x99, 0x92, 0x9f, 0xc0, 0xe5, 0x17, 0x65, 0x0c, 0x86, 0x34, 0xc6, 0x90, 0x59, 0x75,
	0x45, 0x0c, 0xae, 0xdc, 0x42, 0x82, 0xee, 0x20, 0x63, 0x5f, 0xa0, 0xc8, 0x94, 0x34, 0xc0, 0xdc,
	0x7a, 0x3b, 0x88, 0xbe, 0x87, 0x0f, 0x6c, 0x66, 0x4a, 0x4b, 0xab, 0x1b, 0x77, 0x3d, 0x67, 0xe6,
	0x9e, 0x2f, 0x3d, 0x77, 0xa0, 0x4b, 0xa8, 0x13, 0x3d, 0x4e, 0x09, 0x0d, 0x72, 0x6f, 0x95, 0x0a,
	0x1f, 0x5a, 0xd3, 0x43, 0x1c, 0x2b, 0xe2, 0x57, 0xd0, 0x94, 0xd1, 0x71, 0xc8, 0x46, 0x2c, 0xf8,
	0x2f, 0xed, 0xa7, 0xd8, 0x40, 0x3f, 0xa4, 0x28, 0x8e, 0x93, 0xd7, 0x39, 0xe1, 0x7e, 0xb6, 0x4b,
	0x94, 0x36, 0x5c, 0x14, 0x03, 0xee, 0x66, 0x77, 0x02, 0xe3, 0x55, 0x3a, 0xce, 0x1d, 0x59, 0x44,
	0xdd, 0x40, 0x2b, 0xc4, 0x67, 0xcc, 0xcc, 0xd0, 0x1b, 0xb1, 0xa0, 0x23, 0x4f, 0x2a, 0xf7, 0x97,
	0x48, 0x66, 0xd8, 0x1c, 0xb1, 0xe0, 0x42, 0x9e, 0x94, 0xc0, 0x1a, 0xe8, 0x45, 0xd1, 0xbb, 0xa2,
	0x3f, 0x81, 0x7c, 0x68, 0xdb, 0x89, 0x0a, 0xaa, 0xd4, 0xc5, 0x59, 0x05, 0x57, 0x6a, 0xa1, 0xa1,
	0x37, 0x47, 0x3a, 0x46, 0xb4, 0x96, 0xea, 0xed, 0xa0, 0x32, 0xc3, 0xef, 0x00, 0xc2, 0x88, 0x36,
	0xca, 0xb8, 0x2c, 0xe6, 0xb2, 0x2a, 0xce, 0xf9, 0xdc, 0xe5, 0x79, 0x2e, 0xaf, 0xe2, 0xf0, 0x5b,
	0xe8, 0x48, 0x5b, 0x6d, 0x05, 0x77, 0x36, 0xc4, 0x23, 0x5c, 0x96, 0xbc, 0x2c, 0x45, 0x9d, 0x29,
	0xde, 0x03, 0x6f, 0xb1, 0x75, 0xa0, 0xb6, 0xf4, 0x16, 0x5b, 0xdb, 0x8d, 0x54, 0x51, 0x86, 0xba,
	0xe8, 0x2c, 0x57, 0x93, 0x2f, 0x06, 0xff, 0x5c, 0x10, 0x9f, 0xc2, 0x60, 0x7a, 0x48, 0x76, 0x6b,
	0xa9, 0xf6, 0x68, 0x54, 0x38, 0x5b, 0x9e, 0x22, 0x39, 0xb7, 0xcd, 0xd4, 0xff, 0xc7, 0xbf, 0xae,
	0x79, 0x39, 0x53, 0x34, 0xf8, 0x13, 0xf4, 0x5d, 0xc6, 0x92, 0xf0, 0xe3, 0xb3, 0x98, 0x1f, 0xd8,
	0xbb, 0xbf, 0x36, 0xed, 0xff, 0xb4, 0xf3, 0xbd, 0x88, 0x46, 0xc0, 0xee, 0xd9, 0xaa, 0xe5, 0x9e,
	0xd0, 0xc3, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd4, 0x21, 0x84, 0x56, 0x51, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RoninClient is the client API for Ronin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RoninClient interface {
	BuildRemoteTCPForward(ctx context.Context, in *ForwardRequest, opts ...grpc.CallOption) (*ForwardResponse, error)
	BuildProxyForward(ctx context.Context, opts ...grpc.CallOption) (Ronin_BuildProxyForwardClient, error)
}

type roninClient struct {
	cc *grpc.ClientConn
}

func NewRoninClient(cc *grpc.ClientConn) RoninClient {
	return &roninClient{cc}
}

func (c *roninClient) BuildRemoteTCPForward(ctx context.Context, in *ForwardRequest, opts ...grpc.CallOption) (*ForwardResponse, error) {
	out := new(ForwardResponse)
	err := c.cc.Invoke(ctx, "/bp.Ronin/BuildRemoteTCPForward", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roninClient) BuildProxyForward(ctx context.Context, opts ...grpc.CallOption) (Ronin_BuildProxyForwardClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Ronin_serviceDesc.Streams[0], "/bp.Ronin/BuildProxyForward", opts...)
	if err != nil {
		return nil, err
	}
	x := &roninBuildProxyForwardClient{stream}
	return x, nil
}

type Ronin_BuildProxyForwardClient interface {
	Send(*TrafficFromClient) error
	Recv() (*TrafficFromServer, error)
	grpc.ClientStream
}

type roninBuildProxyForwardClient struct {
	grpc.ClientStream
}

func (x *roninBuildProxyForwardClient) Send(m *TrafficFromClient) error {
	return x.ClientStream.SendMsg(m)
}

func (x *roninBuildProxyForwardClient) Recv() (*TrafficFromServer, error) {
	m := new(TrafficFromServer)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RoninServer is the server API for Ronin service.
type RoninServer interface {
	BuildRemoteTCPForward(context.Context, *ForwardRequest) (*ForwardResponse, error)
	BuildProxyForward(Ronin_BuildProxyForwardServer) error
}

func RegisterRoninServer(s *grpc.Server, srv RoninServer) {
	s.RegisterService(&_Ronin_serviceDesc, srv)
}

func _Ronin_BuildRemoteTCPForward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoninServer).BuildRemoteTCPForward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bp.Ronin/BuildRemoteTCPForward",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoninServer).BuildRemoteTCPForward(ctx, req.(*ForwardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ronin_BuildProxyForward_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RoninServer).BuildProxyForward(&roninBuildProxyForwardServer{stream})
}

type Ronin_BuildProxyForwardServer interface {
	Send(*TrafficFromServer) error
	Recv() (*TrafficFromClient, error)
	grpc.ServerStream
}

type roninBuildProxyForwardServer struct {
	grpc.ServerStream
}

func (x *roninBuildProxyForwardServer) Send(m *TrafficFromServer) error {
	return x.ServerStream.SendMsg(m)
}

func (x *roninBuildProxyForwardServer) Recv() (*TrafficFromClient, error) {
	m := new(TrafficFromClient)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Ronin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bp.Ronin",
	HandlerType: (*RoninServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BuildRemoteTCPForward",
			Handler:    _Ronin_BuildRemoteTCPForward_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BuildProxyForward",
			Handler:       _Ronin_BuildProxyForward_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "ronin.proto",
}
